### ISSUE TITLE
Generate Visual Studio snippets

### ISSUE THREAD

**Issue by pschaeflein** [Sector43/FabricSnippets#1]
I have a small console application that can generate the Visual Studio .snippet file for each entry in the VSCodeFabricSnippets.txt file.

I'm happy to add it to the repo (or a new repo if you want to follow the pattern of ngOfficeUI). Or if you want to wait for the Fabric team to get around to it, that's fine. :)

**Comment by manndave** [comment]
Hey Paul,
Sorry, for some reason I didn't get notified that this was here.  This is great.  I was going to do the same thing, but haven't gotten around to it yet.  I'm open to whatever you want to do.  I have an issue open with the Fabric team about adding the snippets to the official repo, but they haven't moved on it yet.  I'll ping them again.

In the meantime, if you want to do a PR, I'll add the app to the repo and use it to generate the VS snippets.  


Thanks!

**Comment by pschaeflein** [comment]
I haven't looked at your snippets nor the Fabric  release in a bit, so no guarantee the new snippets won't cause an error... :(

**Comment by Sector43** [comment]
Merged.  Thanks, Paul!
